//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolRIA.SaftAnalyser.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolRIA.SaftAnalyser.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;xs:schema elementFormDefault=&quot;qualified&quot; xmlns=&quot;https://servicos.portaldasfinancas.gov.pt/sgdtpf/fileProcessingResult/&quot; xmlns:ns=&quot;https://servicos.portaldasfinancas.gov.pt/sgdtpf/fileProcessingResult/&quot; targetNamespace=&quot;https://servicos.portaldasfinancas.gov.pt/sgdtpf/fileProcessingResult/&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xs:element name=&quot;FileProcResult&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element name=&quot;DocumentInfo&quot; maxOccurs=&quot;unbound [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ficheiroResposta {
            get {
                return ResourceManager.GetString("ficheiroResposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;xs:schema xmlns:ns=&quot;urn:OECD:StandardAuditFile-Tax:PT_1.04_01&quot; xmlns:vc=&quot;http://www.w3.org/2007/XMLSchema-versioning&quot; xmlns:doc=&quot;urn:schemas-basda-org:schema-extensions:documentation&quot; xmlns=&quot;urn:OECD:StandardAuditFile-Tax:PT_1.04_01&quot; attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; id=&quot;SAF-T_PT&quot; targetNamespace=&quot;urn:OECD:StandardAuditFile-Tax:PT_1.04_01&quot; version=&quot;1.04_01&quot; vc:minVersion=&quot;1.0&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///    &lt;x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAFTPT1_04_01 {
            get {
                return ResourceManager.GetString("SAFTPT1_04_01", resourceCulture);
            }
        }
    }
}
